<?php

namespace AppBundle\Repository;

/**
 * salonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class salonRepository extends \Doctrine\ORM\EntityRepository
{
}
