<?php

namespace AppBundle\Repository;

/**
 * TarifsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifsRepository extends \Doctrine\ORM\EntityRepository
{
}
